
#**Transformasi Data Dengan RDBMS**

## **Execute SQL statement di platform Google Colab Cell**

In [18]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [19]:
%%sql
sqlite:///retaila.db

In [20]:
import sqlite3

conn = sqlite3.connect('retaila.db')
cursor = conn.cursor()

cursor.execute("create table IF NOT EXISTS demo(id int, title varchar)")
cursor.execute("insert into demo values (1,'pqr'),(2,'stu')")
conn.commit() # Commit the changes

cursor.execute("select * from demo")
results = cursor.fetchall()

print("Contents of the 'demo' table:")
for row in results:
    print(row)

conn.close()

Contents of the 'demo' table:
(1, 'pqr')
(2, 'stu')
(1, 'pqr')
(2, 'stu')
(1, 'pqr')
(2, 'stu')
(1, 'pqr')
(2, 'stu')

In [21]:
#unzip
#!unzip filename.zip
#!mkdir /content/crowdflower
#!mv "/content/text_emotion.csv" "/content/crowdflower/"

In [22]:
#dataset from original source: https://github.com/rahmadsa/dataset/blob/main/text_emotion.csv
#download overwrite
!wget -N https://github.com/rahmadsa/dataset/blob/main/text_emotion.csv -P /content/crowdflower/

--2026-04-10 02:22:51--  https://github.com/rahmadsa/dataset/blob/main/text_emotion.csv
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘/content/crowdflower/text_emotion.csv’

text_emotion.csv        [  <=>               ] 215.55K   909KB/s    in 0.2s

Last-modified header missing -- time-stamps turned off.
2026-04-10 02:22:52 (909 KB/s) - ‘/content/crowdflower/text_emotion.csv’ saved [220727]

## **Load remote CSV and kedalam SQLITE table**

In [23]:
# load the remote data into a Pandas DataFrame
import pandas as pd
df_cfemotion = pd.read_csv('https://github.com/rahmadsa/dataset/blob/main/text_emotion.csv?raw=true', on_bad_lines='skip', encoding='latin-1')
df_cfemotion

,tweet_id,sentiment,author,content
0,1956967341,empty,xoshayzers,@tiffanylue i know i was listenin to bad habi...
1,1956967666,sadness,wannamama,Layin n bed with a headache ughhhh...waitin o...
2,1956967696,sadness,coolfunky,Funeral ceremony...gloomy friday...
3,1956967789,enthusiasm,czareaquino,wants to hang out with friends SOON!
4,1956968416,neutral,xkilljoyx,@dannycastillo We want to trade with someone w...
...,...,...,...,...
39995,1753918954,neutral,showMe_Heaven,@JohnLloydTaylor
39996,1753919001,love,drapeaux,Happy Mothers Day All my love
39997,1753919005,love,JenniRox,Happy Mother's Day to all the mommies out ther...
39998,1753919043,happiness,ipdaman1,@niariley WASSUP BEAUTIFUL!!! FOLLOW ME!! PEE...
39999,1753919049,love,Alpharalpha,@mopedronin bullet train from tokyo the gf ...

In [24]:
import sqlite3 as sql
conn = sql.connect('/content/cfemotion.db')
df_cfemotion.to_sql('tb_emotion', conn, if_exists='replace', index=False)

40000

In [25]:
#connect to sqlite db and read from sqlite table
import sqlite3 as sql
conn = sql.connect('/content/cfemotion.db')
df_cfemotion = pd.read_sql('SELECT * FROM tb_emotion', conn)
df_cfemotion

,tweet_id,sentiment,author,content
0,1956967341,empty,xoshayzers,@tiffanylue i know i was listenin to bad habi...
1,1956967666,sadness,wannamama,Layin n bed with a headache ughhhh...waitin o...
2,1956967696,sadness,coolfunky,Funeral ceremony...gloomy friday...
3,1956967789,enthusiasm,czareaquino,wants to hang out with friends SOON!
4,1956968416,neutral,xkilljoyx,@dannycastillo We want to trade with someone w...
...,...,...,...,...
39995,1753918954,neutral,showMe_Heaven,@JohnLloydTaylor
39996,1753919001,love,drapeaux,Happy Mothers Day All my love
39997,1753919005,love,JenniRox,Happy Mother's Day to all the mommies out ther...
39998,1753919043,happiness,ipdaman1,@niariley WASSUP BEAUTIFUL!!! FOLLOW ME!! PEE...
39999,1753919049,love,Alpharalpha,@mopedronin bullet train from tokyo the gf ...

## **Loading GoEmotion Dataset ke database Sqlite**

In [17]:
!wget -P /content/ https://archive.org/download/goemotions/goemotions_1.csv
!wget -P /content/ https://archive.org/download/goemotions/goemotions_2.csv
!wget -P /content/ https://archive.org/download/goemotions/goemotions_3.csv

--2026-04-10 02:22:37--  https://archive.org/download/goemotions/goemotions_1.csv
Resolving archive.org (archive.org)... 207.241.224.2
Connecting to archive.org (archive.org)|207.241.224.2|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://dn721608.ca.archive.org/0/items/goemotions/goemotions_1.csv [following]
--2026-04-10 02:22:38--  https://dn721608.ca.archive.org/0/items/goemotions/goemotions_1.csv
Resolving dn721608.ca.archive.org (dn721608.ca.archive.org)... 204.62.247.27
Connecting to dn721608.ca.archive.org (dn721608.ca.archive.org)|204.62.247.27|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14174600 (14M) [text/csv]
Saving to: ‘/content/goemotions_1.csv’

goemotions_1.csv    100%[===================>]  13.52M  17.4MB/s    in 0.8s

2026-04-10 02:22:40 (17.4 MB/s) - ‘/content/goemotions_1.csv’ saved [14174600/14174600]

--2026-04-10 02:22:40--  https://archive.org/download/goemotions/goemotions_2.csv
Resolving archive.org (archive.org)... 207.241.224.2
Connecting to archive.org (archive.org)|207.241.224.2|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://dn721608.ca.archive.org/0/items/goemotions/goemotions_2.csv [following]
--2026-04-10 02:22:40--  https://dn721608.ca.archive.org/0/items/goemotions/goemotions_2.csv
Resolving dn721608.ca.archive.org (dn721608.ca.archive.org)... 204.62.247.27
Connecting to dn721608.ca.archive.org (dn721608.ca.archive.org)|204.62.247.27|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14173154 (14M) [text/csv]
Saving to: ‘/content/goemotions_2.csv’

goemotions_2.csv    100%[===================>]  13.52M  16.8MB/s    in 0.8s

2026-04-10 02:22:42 (16.8 MB/s) - ‘/content/goemotions_2.csv’ saved [14173154/14173154]

--2026-04-10 02:22:42--  https://archive.org/download/goemotions/goemotions_3.csv
Resolving archive.org (archive.org)... 207.241.224.2
Connecting to archive.org (archive.org)|207.241.224.2|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://dn721608.ca.archive.org/0/items/goemotions/goemotions_3.csv [following]
--2026-04-10 02:22:42--  https://dn721608.ca.archive.org/0/items/goemotions/goemotions_3.csv
Resolving dn721608.ca.archive.org (dn721608.ca.archive.org)... 204.62.247.27
Connecting to dn721608.ca.archive.org (dn721608.ca.archive.org)|204.62.247.27|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14395164 (14M) [text/csv]
Saving to: ‘/content/goemotions_3.csv’

goemotions_3.csv    100%[===================>]  13.73M  1.84MB/s    in 7.8s

2026-04-10 02:22:51 (1.77 MB/s) - ‘/content/goemotions_3.csv’ saved [14395164/14395164]

In [26]:
# load the remote data into a Pandas DataFrame
import pandas as pd
df_goemotions1 = pd.read_csv('https://github.com/rahmadsa/dataset/blob/main/goemotions_1.csv', on_bad_lines='skip', encoding='latin-1')
df_goemotions1[1:3]

                                     <!DOCTYPE html>
1                                          lang="en"
2    data-color-mode="auto" data-light-theme="lig...

In [27]:
# load the remote data into a Pandas DataFrame
import pandas as pd
df_goemotions2 = pd.read_csv('https://github.com/rahmadsa/dataset/blob/main/goemotions_2.csv', on_bad_lines='skip', encoding='latin-1')
df_goemotions2[1:3]

                                     <!DOCTYPE html>
1                                          lang="en"
2    data-color-mode="auto" data-light-theme="lig...

In [28]:
# load the remote data into a Pandas DataFrame
import pandas as pd
df_goemotions3 = pd.read_csv('https://github.com/rahmadsa/dataset/blob/main/goemotions_3.csv', on_bad_lines='skip', encoding='latin-1')
df_goemotions3[1:3]

                                     <!DOCTYPE html>
1                                          lang="en"
2    data-color-mode="auto" data-light-theme="lig...

In [29]:
#connect to sqlite db and send csv data to sqlite table
import sqlite3 as sql
conn = sql.connect('/content/goemotions.db')

df_goemotions1.to_sql('tb_goemotions', conn, if_exists='append', index = False)
df_goemotions2.to_sql('tb_goemotions', conn, if_exists='append', index = False)
df_goemotions3.to_sql('tb_goemotions', conn, if_exists='append', index = False)

1045

In [30]:
#connect to sqlite db and read from sqlite table
import sqlite3 as sql
conn = sql.connect('/content/goemotions.db')
df_goemotions = pd.read_sql('SELECT * FROM tb_goemotions', conn)
df_goemotions

                                        <!DOCTYPE html>
0                                                 <html
1                                             lang="en"
2       data-color-mode="auto" data-light-theme="lig...
3       data-a11y-animated-images="system" data-a11y...
4                                                     >
...                                                 ...
3130                                             </div>
3131      <div id="js-global-screen-reader-notice" c...
3132      <div id="js-global-screen-reader-notice-as...
3133                                            </body>
3134                                            </html>

[3135 rows x 1 columns]

##**Import Database File Sqlite**

Mengunduh suatu berkas dari internet adalah hal yang umum, baik untuk data backup, pengunduhan laporan, atau mengambil sumber data untuk analisis. Pengunduhan berkas dapat dilakukan secara manual satu per satu. Kita dapat menyederhanakan prosesnya dengan mengotomatiskannya menggunakan pemrograman Python.

Sebagai contoh kita akan mengunduh file dengan URL sebagai berikut:

https://github.com/rahmadsa/dataset/blob/main/Car_Database.db

Berikut adalah contoh potongan script untuk mengunduh data dari suatu URL di internet. File download akan di simpan pada folder '/content/' pada colabs folder

In [31]:
import requests
#URL file
path = "https://github.com/rahmadsa/dataset/raw/refs/heads/main/Car_Database.db"

req = requests.get(path, stream=True)
url_content = req.content

db_file_name = 'Car_Database.db'
db_file = open(db_file_name, 'wb')

db_file.write(url_content)
db_file.close()

##**Check Database File Sqlite**

Untuk melihat daftar tabel dari suatu database SQLite, kita bisa menggunakan perintah ‘.tables’ jika berinteraksi melalui shell baris perintah sqlite3.

Kita bisa menggunakan kueri pada tabel sqlite_master dengan “SELECT name FROM sqlite_master WHERE type=’table’;”. Di sinilah SQLite menyimpan metadata tentang semua tabel di database kita

In [32]:
import sqlite3

#folder file pada google drive
folder = '/content/'
namafileDB = 'Car_Database.db'
conn = sqlite3.connect(folder+namafileDB)  # Replace 'your_database.db' with the actual database file name
cursor = conn.cursor()

#check table - table dalam suatu database
cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")

results = cursor.fetchall()
for row in results:
    print(row)

('Customers',)
('sqlite_sequence',)
('Models',)
('Customer_Ownership',)
('Dealer_Brand',)
('Car_Parts',)
('Manufacture_Plant',)
('Brands',)
('Dealers',)
('Car_Options',)
('Car_Vins',)

Untuk melihat data salah satu table pada salah satu table menggunakan perintah sebagai berikut.

In [33]:
#check isi salah satu table dalam database
print("Daftar isi Tabel Model : ")
cursor.execute("SELECT * FROM Models LIMIT 10")
results = cursor.fetchall()
for row in results:
    print(row)

conn.close()

Daftar isi Tabel Model :
(1, 'The Blonde', 23000, 1)
(2, 'The Brunette', 25000, 1)
(3, 'The Red Head', 29000, 1)
(4, 'Hat', 22000, 2)
(5, 'Sweater', 25000, 2)
(6, 'T-Shirt', 27000, 2)
(7, 'Orange', 15000, 3)
(8, 'Blue', 12000, 3)
(9, 'Green', 17000, 3)
(10, 'LaFerrari', 125000, 4)

**Tugas Praktek 5a :**

................

**Tugas Praktek 5b :**

................

**Jawab :**

..